# Minimal unified configuration
system:
  project_name: "ano-rag"  # default project name
  seed: 42                 # random seed
  device: "cpu"            # computation device

document:
  chunk_size: 256          # default chunk size
  overlap: 32              # overlap between chunks

embedding:
  model_name: "BAAI/bge-m3"  # embedding model name
  batch_size: 64             # embedding batch size
  max_length: 512            # max token length
  normalize: true            # whether to normalize vectors

retrieval:
  candidate_pool: 50        # global candidate pool size
  hybrid:
    enabled: true
    fusion_method: "linear"  # linear|rrf|weighted_sum
    weights:
      dense: 1.0
      bm25: 0.5
      graph: 0.5
      path: 0.1
    rrf_k: 60               # only used for rrf
  bm25:
    k1: 1.2
    b: 0.75
    text_field: "title_raw_span"
  graph:
    enabled: true
    k_hop: 2
    expand_top_m: 20

path_aware:
  enabled: true
  min_path_score: 0.3

dispatcher:
  final_semantic_count: 8
  final_graph_count: 5
  bridge_policy: "keepalive"  # none|keepalive|boost
  bridge_boost_epsilon: 0.02
  debug_log: true

llm:
  provider: "openai"
  temperature: 0.7
  max_output_tokens: 512

guardrail:
  enabled: true
  min_results: 1
  min_score: 0.0
  timeout_seconds: 30
