# ANO-RAG 系统统一配置文件
# 本配置文件包含了向量检索增强生成系统的所有核心参数

# 系统基础配置
system:
  project_name: "ano-rag"  # 项目名称，用于标识和日志记录
  # seed: 42                 # 随机种子，确保实验结果可复现
  device: "cuda"            # 计算设备：cpu/cuda，影响模型推理速度

# 文档处理配置
document:
  chunk_size: 256          # 文档分块大小（字符数），影响检索粒度
  overlap: 32              # 分块间重叠字符数，保证语义连续性

# 嵌入模型配置
embedding:
  model_name: "BAAI/bge-m3"  # 嵌入模型名称，支持中英文多语言
  batch_size: 64             # 批处理大小，影响嵌入生成速度
  max_length: 512            # 最大token长度，超出部分会被截断
  normalize: true            # 是否对向量进行归一化，提高相似度计算准确性

# 向量存储配置
vector_store:
  top_k: 20                 # 检索候选数量，影响召回率和计算开销
  similarity_threshold: 0.15 # 相似度阈值，低阈值提高召回率但可能引入噪声
  batch_size: 64            # 向量检索批处理大小
  dimension: 1024           # 向量维度，需与嵌入模型匹配
  index_type: "IVFFlat"     # FAISS索引类型，影响检索速度和精度
  nlist: 20                 # IVF索引聚类数量，避免训练数据不足警告
  similarity_metric: "cosine" # 相似度计算方法：cosine/euclidean/dot_product

# 检索策略配置
retrieval:
  candidate_pool: 80        # 全局候选池大小，影响最终检索质量
  min_per_subq: 1          # 每个子问题最小召回数量，硬约束
  # 性能控制配置
  performance:
    max_fallback_per_step: 8      # 每个回补步骤的最大候选数量
    max_graph_expansion: 15        # 图扩展的最大候选数量
    max_entity_lookup: 12          # 实体查找的最大实体数量
    fallback_timeout_ms: 1000     # 回补检索超时时间（毫秒）
    max_total_fallback: 10        # 总回补候选数量上限
  # 图感知两阶段rerank配置
  use_graph_rerank: true    # 是否启用图感知两阶段rerank
  seeds_semantic: 50        # 语义检索种子节点数量
  seeds_bm25: 30           # BM25检索种子节点数量
  subgraph_radius: 2       # 子图截取半径
  edge_thresh: 0.35        # 边权阈值过滤
  k_paths: 20              # 生成路径数量上限
  pick_paths: 4            # 选择路径数量
  overlap_thresh: 0.5      # 路径重叠阈值
  token_budget: 1800       # token预算
  alpha: 0.5               # 终点相似度权重
  beta: 0.3                # 路径平均权重
  gamma: 0.2               # 上下文覆盖权重
  rho: 0.25                # 上下文覆盖上限
  lambda_len: 0.05         # 路径长度惩罚系数
  query_mode: auto         # 查询模式：precise/explanatory/auto
  hybrid:                   # 混合检索配置
    enabled: true           # 是否启用混合检索（向量+BM25+图谱）
    fusion_method: "linear"  # 融合方法：linear线性加权|rrf倒数排名融合|weighted_sum加权求和
    weights:                # 各检索方法权重配置
      dense: 1.0            # 密集向量检索权重
      bm25: 0.5             # BM25关键词检索权重
      graph: 0.65            # 知识图谱检索权重
  # 重排权重配置
  rerank:
    entity_overlap_weight: 0.4     # 实体重叠打分权重
    path_consistency_weight: 0.3   # 链路一致性打分权重
    semantic_weight: 0.35           # 语义相似度权重
    soft_penalty_no_entity: 0.7    # 无实体命中时的软惩罚系数
    rrf_k: 60               # RRF融合参数，仅在fusion_method为rrf时使用
  bm25:                     # BM25检索参数
    k1: 1.2                 # 词频饱和参数，控制词频对得分的影响
    b: 0.75                 # 文档长度归一化参数
    text_field: "title_raw_span" # BM25检索的文本字段
  graph:                    # 图谱检索配置
    enabled: true           # 是否启用知识图谱检索
    k_hop: 4                # 图谱遍历跳数，影响关联实体发现范围
    expand_top_m: 50        # 图谱扩展的top-m候选数量
    expand_k: 1             # 图扩展时的一跳扩展限制
    db_path: "data/graph.db"  # 图数据库路径
    max_depth: 2            # 图遍历最大深度
    min_score: 0.3          # 最小相关性分数阈值
    max_nodes: 50           # 单次查询最大节点数
  multi_hop:                # 多跳检索配置
    enabled: true           # 是否启用多跳检索（false时使用混合图检索策略）
    # 图检索策略配置
    strategy: "hybrid"       # 图检索策略：entity_extraction|top_k_seed|hybrid
    top_k_seed:             # Top-K种子节点策略配置
      enabled: false       # 是否启用Top-K种子节点策略
      seed_count: 5         # 作为种子节点的Top-K数量
      fallback_to_entity: true  # 当Top-K结果不足时是否回退到实体提取策略
    entity_extraction:      # 实体提取策略配置（传统方式）
      enabled: true         # 是否启用实体提取策略
      max_entities: 10      # 最大提取实体数量
    hybrid_mode:            # 混合策略配置
      primary_strategy: "entity_extraction"  # 主策略：entity_extraction|top_k_seed
      fallback_strategy: "top_k_seed"       # 备用策略
      switch_threshold: 3   # 主策略结果不足时的切换阈值

# 路径感知检索配置
path_aware:
  enabled: true            # 是否启用路径感知检索，提高多跳推理能力
  min_path_score: 0.05       # 最小路径得分阈值

# 结果分发器配置
dispatcher:
  final_semantic_count: 7   # 最终语义检索结果数量（减少）
  final_graph_count: 30      # 最终图谱检索结果数量（增加）
  bridge_policy: "boost"  # 桥接策略：none无|keepalive保活|boost增强
  bridge_boost_epsilon: 0.03  # 桥接增强的epsilon参数
  debug_log: true           # 是否输出调试日志

# 调度器配置
scheduler:
  coverage_guard: true      # 是否启用覆盖守卫，确保每个子问题至少有一条证据

# 大语言模型配置
llm:
  provider: "hybrid_llm"      # LLM提供商：lmstudio/openai/ollama/hybrid_llm等
  model: "openai/gpt-oss-20b"   # 模型名称，需与provider匹配
  temperature: 0.1          # 生成温度，控制输出随机性（0-1）
  max_output_tokens: 8192    # 最大输出token数量
  
  # 混合LLM配置（当provider为hybrid_llm时生效）
  hybrid_llm:
    mode: "task_division"    # 混合模式：task_division任务划分|competitive竞争模式
    
    # 轻量级任务配置（使用Ollama）
    light_tasks:
      model: "qwen2.5:latest" # 轻量级任务模型
      base_url: "http://localhost:11434"  # Ollama服务地址
      timeout: 30             # 请求超时时间（秒）
      max_async: 16            # 最大异步请求数
      # max_tokens: 1024        # 最大输出token数
      num_ctx: 32768           # 上下文窗口大小
      temperature: 0.1        # 生成温度
    
    # 重量级任务配置（使用LM Studio）
    heavy_tasks:
      provider: "lmstudio"    # 重量级任务提供商
      model: "openai/gpt-oss-20b"  # 重量级任务模型
      base_url: "http://localhost:1234/v1"  # LM Studio服务地址
      instances: 2            # LM Studio实例数量
      timeout: 60             # 请求超时时间（秒）

# 检索护栏配置
guardrail:
  enabled: false             # 是否启用检索护栏，防止低质量结果
  min_results: 1            # 最少检索结果数量
  min_score: 0.0            # 最低检索得分阈值
  timeout_seconds: 30       # 检索超时时间（秒）

# 新增功能配置开关
feature_switches:
  # 稳定note_id生成功能
  stable_note_id:
    enabled: true           # 是否启用基于源文档信息的稳定note_id生成
    use_content_hash: true  # 是否使用内容哈希作为备选方案
    fallback_to_index: true # 无其他信息时是否回退到索引方式

# 增强关系提取配置
enhanced_relation_extraction:
  use_llm_extraction: true     # 是否启用LLM增强的语义关系提取
  use_fast_model: true          # 是否使用快速模型
  enable_topic_groups: true     # 是否启用主题组关系提取
  enable_reasoning_paths: false  # 是否启用推理路径关系提取
  
  # 轻量级关系类型功能
  lightweight_relations:
    enabled: true           # 是否启用轻量级商业关系识别
    relation_types:         # 支持的关系类型配置
      succession: true      # 继任关系
      acquisition: true     # 收购关系
      ownership: true       # 归属关系
      subsidiary: true      # 子公司关系
      partnership: true     # 合作关系
      merger: true          # 合并关系
    keyword_matching: true  # 是否启用关键词匹配
    pattern_matching: true  # 是否启用模式匹配
  
  # 一致性检查功能
  consistency_check:
    enabled: true           # 是否启用数据写入前的一致性检查
    strict_mode: false      # 严格模式：发现严重错误时停止处理
    check_note_id: true     # 检查note_id一致性
    check_entity_alignment: true  # 检查实体对齐
    check_relation_chains: true   # 检查关系链完整性
    check_source_binding: true    # 检查源文档绑定稳定性
    check_graph_structure: true   # 检查图结构完整性
    entity_alignment_threshold: 0.8  # 实体对齐警告阈值（80%实体缺失才警告）
    export_report: true     # 是否导出检查报告
    report_format: "json"   # 报告格式：json/yaml/txt
