# 实体和谓词标准化器自定义规则配置
# 这个文件包含了实体和谓词标准化器的自定义规则和映射

# 实体标准化器自定义规则
entity_normalizer:
  # 自定义规则
  custom_rules:
    # 公司名称标准化
    company_normalization:
      - pattern: "(.+?)(?:有限公司|股份有限公司|集团有限公司)"
        replacement: "\\1"
        description: "移除公司后缀"
      - pattern: "(.+?)(?:Co\\.,?\\s*Ltd\\.?|Corporation|Corp\\.?|Inc\\.?|LLC)"
        replacement: "\\1"
        description: "移除英文公司后缀"
    
    # 地名标准化
    location_normalization:
      - pattern: "(.+?)(?:市|省|县|区|自治区|特别行政区)"
        replacement: "\\1"
        description: "移除行政区划后缀"
      - pattern: "(.+?)(?:State|Province|City|County|District)"
        replacement: "\\1"
        description: "移除英文行政区划后缀"
    
    # 人名标准化
    person_normalization:
      - pattern: "(.+?)(?:先生|女士|博士|教授|总裁|CEO|CTO|CFO)"
        replacement: "\\1"
        description: "移除人名称谓"
      - pattern: "(.+?)(?:Mr\\.|Mrs\\.|Ms\\.|Dr\\.|Prof\\.)"
        replacement: "\\1"
        description: "移除英文称谓"
    
    # 空格和标点标准化
    whitespace_normalization:
      - pattern: "\\s+"
        replacement: " "
        description: "多余空格合并为单个空格"
      - pattern: "[\u00A0\u2000-\u200B\u2028\u2029\u202F\u205F\u3000]"
        replacement: " "
        description: "特殊空格字符标准化为普通空格"
  
  # 实体类型映射
  entity_type_mapping:
    PERSON: ["人物", "人员", "个人", "用户", "客户", "员工"]
    ORGANIZATION: ["组织", "机构", "公司", "企业", "团队", "部门"]
    LOCATION: ["地点", "位置", "地区", "城市", "国家", "省份"]
    TIME: ["时间", "日期", "年份", "月份", "时刻", "期间"]
    EVENT: ["事件", "活动", "会议", "项目", "任务", "计划"]
    CONCEPT: ["概念", "理论", "方法", "技术", "知识", "原理"]
    PRODUCT: ["产品", "商品", "服务", "软件", "系统", "平台"]
    DOCUMENT: ["文档", "文件", "报告", "资料", "记录", "档案"]

# 谓词标准化器自定义规则
predicate_normalizer:
  # 自定义规则
  custom_rules:
    # 动作谓词标准化
    action_normalization:
      - pattern: "创建|建立|成立|创立|建造"
        replacement: "创建"
        description: "创建类动作标准化"
      - pattern: "拥有|持有|具有|包含|含有"
        replacement: "拥有"
        description: "拥有类关系标准化"
      - pattern: "位于|在|处于|坐落于"
        replacement: "位于"
        description: "位置关系标准化"
      - pattern: "属于|隶属于|归属于|从属于"
        replacement: "属于"
        description: "归属关系标准化"
    
    # 关系谓词标准化
    relation_normalization:
      - pattern: "导致|引起|造成|产生|带来"
        replacement: "导致"
        description: "因果关系标准化"
      - pattern: "影响|作用于|改变|左右"
        replacement: "影响"
        description: "影响关系标准化"
      - pattern: "相关|关联|联系|关系"
        replacement: "相关"
        description: "关联关系标准化"
      - pattern: "等于|为|就是|即是"
        replacement: "等于"
        description: "等价关系标准化"
  
  # 谓词权重配置
  predicate_weights:
    "创建": 0.9
    "拥有": 0.8
    "位于": 0.8
    "属于": 0.9
    "导致": 0.7
    "影响": 0.6
    "相关": 0.5
    "等于": 1.0
    "包含": 0.8
    "来自": 0.7
    "参与": 0.6
    "使用": 0.6
    "产生": 0.7
    "需要": 0.6
    "支持": 0.5
  
  # 谓词分类
  predicate_categories:
    action: ["创建", "建立", "制造", "生产", "开发"]
    possession: ["拥有", "持有", "包含", "具有"]
    location: ["位于", "在", "处于", "坐落"]
    membership: ["属于", "隶属", "归属", "从属"]
    causation: ["导致", "引起", "造成", "产生"]
    influence: ["影响", "作用", "改变", "左右"]
    relation: ["相关", "关联", "联系", "关系"]
    equivalence: ["等于", "为", "就是", "即是"]