# 图提取器配置
# 这个文件包含了路径感知排序器中图提取器的配置

# 图提取器配置
graph_extractor:
  # 实体提取配置
  entity_extraction:
    # 实体提取模式
    entity_patterns:
      - "(.+?)是(.+?)"
      - "(.+?)属于(.+?)"
      - "(.+?)包含(.+?)"
      - "(.+?)位于(.+?)"
      - "(.+?)来自(.+?)"
      - "(.+?)的(.+?)"
    
    # 实体类型映射
    entity_type_mapping:
      人物: ["人", "人员", "个人", "用户", "客户"]
      组织: ["公司", "企业", "机构", "组织", "团队"]
      地点: ["地方", "位置", "地区", "城市", "国家"]
      时间: ["时间", "日期", "年份", "月份", "时刻"]
      事件: ["事件", "活动", "会议", "项目", "任务"]
      概念: ["概念", "理论", "方法", "技术", "知识"]
  
  # 关系提取配置
  relation_extraction:
    # 谓词映射
    predicate_mapping:
      "是": ["等于", "为", "就是", "即"]
      "有": ["拥有", "具有", "包含", "含有"]
      "在": ["位于", "处于", "存在于"]
      "属于": ["归属于", "隶属于", "从属于"]
      "来自": ["源于", "出自", "起源于"]
      "导致": ["引起", "造成", "产生", "带来"]
      "影响": ["作用于", "改变", "左右"]
      "关联": ["相关", "联系", "关系"]
    
    # 关系模式
    relation_patterns:
      - "(.+?)和(.+?)之间的关系"
      - "(.+?)对(.+?)的影响"
      - "(.+?)与(.+?)相关"
      - "(.+?)导致(.+?)"
      - "(.+?)属于(.+?)"
      - "(.+?)包含(.+?)"
      - "(.+?)位于(.+?)"
      - "(.+?)来自(.+?)"
    
    # 关系权重配置
    relation_weights:
      "是": 1.0
      "有": 0.9
      "在": 0.8
      "属于": 0.9
      "来自": 0.7
      "导致": 0.8
      "影响": 0.7
      "关联": 0.6
      "相关": 0.6
      "包含": 0.8
      "位于": 0.8
    
    # 置信度阈值
    confidence_threshold: 0.5
    
    # 最大提取数量
    max_extractions: 100
    
    # 去重配置
    deduplication:
      enabled: true
      similarity_threshold: 0.85
      method: "semantic"  # semantic, exact, fuzzy