# 实体标准化规则配置
# 这个文件包含了实体标准化的各种规则配置

# 标准化规则配置
normalization_rules:
  # 公司名称规则
  company_suffixes:
    enabled: true
    confidence: 0.9
    patterns:
      - "(.+?)(?:有限公司|有限责任公司|股份有限公司|集团有限公司)"
      - "(.+?)(?:Co\\.?\\s*Ltd\\.?|Corporation|Corp\\.?|Inc\\.?|LLC)"
  
  # 地名规则
  location_suffixes:
    enabled: true
    confidence: 0.8
    patterns:
      - "(.+?)(?:市|省|县|区|自治区|特别行政区)"
  
  # 人名规则
  person_titles:
    enabled: true
    confidence: 0.7
    patterns:
      - "(.+?)(?:先生|女士|教授|博士|院士|主席|总裁|CEO)"
  
  # 标点和空格规则
  punctuation:
    enabled: true
    confidence: 1.0
    patterns:
      - "\\s+"  # 多个空格合并为一个
      - "[，。；：！？、]"  # 移除中文标点