# 离线标准化配置文件

# 实体谓词标准化器配置
normalizer:
  entity_normalizer:
    # 模糊匹配阈值
    fuzzy_threshold: 0.8
    # 是否启用模糊匹配
    enable_fuzzy_matching: true
    # 是否区分大小写
    case_sensitive: false
    # 别名字典文件路径
    alias_dict_path: "config/entity_aliases.json"
    # 是否启用动态别名学习
    enable_dynamic_aliases: true
    # 最小实体长度
    min_entity_length: 2
    # 最大实体长度
    max_entity_length: 50
    
  predicate_normalizer:
    # 模糊匹配阈值
    fuzzy_threshold: 0.8
    # 是否启用模糊匹配
    enable_fuzzy_matching: true
    # 是否区分大小写
    case_sensitive: false
    # 谓词映射文件路径
    predicate_mapping_path: "config/predicate_mapping.json"
    # 谓词分类文件路径
    predicate_categories_path: "config/predicate_categories.json"
    # 最小谓词长度
    min_predicate_length: 2
    # 最大谓词长度
    max_predicate_length: 30

# 实体提取配置
entity_extraction:
  # 是否启用命名实体识别
  enable_ner: true
  # 是否启用正则表达式提取
  enable_regex: true
  # 最小置信度阈值
  min_confidence: 0.5
  # 实体类型过滤
  entity_types:
    - PERSON
    - ORGANIZATION
    - LOCATION
    - PRODUCT
    - EVENT
    - DATE
    - MONEY
    - PERCENT

# 谓词提取配置
predicate_extraction:
  # 是否启用关系抽取
  enable_relation_extraction: true
  # 是否启用正则表达式提取
  enable_regex: true
  # 最小置信度阈值
  min_confidence: 0.5
  # 目标谓词类型
  target_predicates:
    - founded
    - co_founded
    - located_in
    - works_for
    - member_of
    - part_of
    - instance_of
    - related_to

# 处理配置
processing:
  # 批处理大小
  batch_size: 100
  # 是否启用并行处理
  enable_parallel: false
  # 并行进程数
  num_processes: 4
  # 是否保存中间结果
  save_intermediate: true
  # 中间结果保存间隔
  save_interval: 1000

# 质量控制配置
quality_control:
  # 最小实体数量
  min_entities_per_note: 0
  # 最大实体数量
  max_entities_per_note: 20
  # 最小谓词数量
  min_predicates_per_note: 0
  # 最大谓词数量
  max_predicates_per_note: 10
  # 是否启用重复检测
  enable_duplicate_detection: true
  # 是否启用噪声过滤
  enable_noise_filtering: true

# 日志配置
logging:
  # 日志级别
  level: INFO
  # 是否启用详细日志
  verbose: false
  # 统计报告间隔
  stats_interval: 100
  # 是否保存处理日志
  save_processing_log: true
  # 日志文件路径
  log_file_path: "logs/offline_normalization.log"

# 输出配置
output:
  # 输出格式
  format: json
  # 是否美化输出
  pretty_print: true
  # 是否包含元数据
  include_metadata: true
  # 是否包含统计信息
  include_stats: true
  # 备份原始数据
  backup_original: true