# 检索保障配置
# 这个文件包含了检索保障系统的完整配置

# 检索保障配置
retrieval_guardrail:
  # 基本配置
  guardrail_level: "standard"       # 保障级别: strict, standard, relaxed
  min_results: 3                    # 最少结果数
  max_results: 100                  # 最大结果数
  timeout_seconds: 30               # 超时时间(秒)
  
  # 质量保障配置
  quality_assurance:
    enabled: true                   # 启用质量保障
    min_quality_score: 0.6          # 最小质量分数
    quality_factors:
      relevance: 0.4                # 相关性权重
      completeness: 0.3             # 完整性权重
      accuracy: 0.2                 # 准确性权重
      freshness: 0.1                # 新鲜度权重
    
    # 质量评估方法
    assessment_methods:
      relevance:
        method: "semantic_similarity" # 语义相似度评估
        threshold: 0.7              # 相关性阈值
        model: "sentence-transformers/all-MiniLM-L6-v2"
      
      completeness:
        method: "coverage_analysis"   # 覆盖度分析
        min_coverage: 0.8           # 最小覆盖度
        key_concepts_threshold: 0.9  # 关键概念覆盖阈值
      
      accuracy:
        method: "fact_verification"   # 事实验证
        confidence_threshold: 0.8   # 置信度阈值
        enable_cross_validation: true # 启用交叉验证
      
      freshness:
        method: "temporal_analysis"   # 时间分析
        max_age_days: 365           # 最大年龄(天)
        prefer_recent: true         # 偏好最新内容
  
  # 内容过滤配置
  content_filtering:
    enabled: true                   # 启用内容过滤
    
    # 有害内容过滤
    harmful_content:
      enabled: true                 # 启用有害内容过滤
      categories: ["hate", "violence", "adult", "spam"]
      confidence_threshold: 0.8     # 置信度阈值
      action: "remove"              # 处理动作: remove, flag, warn
    
    # 重复内容过滤
    duplicate_content:
      enabled: true                 # 启用重复内容过滤
      similarity_threshold: 0.9     # 相似度阈值
      method: "semantic"            # 去重方法: exact, fuzzy, semantic
      keep_strategy: "highest_score" # 保留策略: first, last, highest_score
    
    # 低质量内容过滤
    low_quality_content:
      enabled: true                 # 启用低质量内容过滤
      min_length: 50                # 最小长度
      max_length: 10000             # 最大长度
      min_word_count: 10            # 最小词数
      language_detection: true      # 启用语言检测
      supported_languages: ["zh", "en"] # 支持的语言
  
  # 多样性保障配置
  diversity_assurance:
    enabled: true                   # 启用多样性保障
    min_diversity_score: 0.5        # 最小多样性分数
    
    # 语义多样性
    semantic_diversity:
      enabled: true                 # 启用语义多样性
      min_distance: 0.3             # 最小语义距离
      clustering_threshold: 0.7     # 聚类阈值
      max_cluster_size: 5           # 最大聚类大小
    
    # 来源多样性
    source_diversity:
      enabled: true                 # 启用来源多样性
      max_per_source: 30            # 每个来源最大数量
      min_sources: 2                # 最小来源数量
      source_balance_threshold: 0.6 # 来源平衡阈值
    
    # 主题多样性
    topic_diversity:
      enabled: true                 # 启用主题多样性
      min_topics: 2                 # 最小主题数量
      topic_balance_threshold: 0.5  # 主题平衡阈值
      topic_extraction_method: "keyword" # 主题提取方法
  
  # 安全保障配置
  security_guardrails:
    enabled: true                   # 启用安全保障
    
    # 隐私保护
    privacy_protection:
      enabled: true                 # 启用隐私保护
      pii_detection: true           # 启用个人信息检测
      pii_categories: ["email", "phone", "ssn", "credit_card"]
      anonymization: true           # 启用匿名化
      action: "mask"                # 处理动作: remove, mask, encrypt
    
    # 敏感信息过滤
    sensitive_info_filtering:
      enabled: true                 # 启用敏感信息过滤
      categories: ["financial", "medical", "legal", "confidential"]
      confidence_threshold: 0.7     # 置信度阈值
      action: "flag"                # 处理动作: remove, flag, encrypt
    
    # 访问控制
    access_control:
      enabled: false                # 启用访问控制
      require_authentication: false # 需要身份验证
      role_based_filtering: false   # 基于角色的过滤
      content_classification: false # 内容分类
  
  # 性能保障配置
  performance_guardrails:
    enabled: true                   # 启用性能保障
    
    # 响应时间保障
    response_time:
      max_response_time: 5.0        # 最大响应时间(秒)
      timeout_action: "partial_results" # 超时动作: error, partial_results, cached
      enable_caching: true          # 启用缓存
      cache_ttl: 3600               # 缓存生存时间(秒)
    
    # 资源使用保障
    resource_usage:
      max_memory_mb: 1024           # 最大内存使用(MB)
      max_cpu_percent: 80           # 最大CPU使用率(%)
      enable_monitoring: true       # 启用监控
      alert_threshold: 0.9          # 告警阈值
    
    # 并发控制
    concurrency_control:
      max_concurrent_requests: 10   # 最大并发请求数
      rate_limiting: true           # 启用速率限制
      requests_per_minute: 100      # 每分钟请求数
      burst_limit: 20               # 突发限制
  
  # 回退策略配置
  fallback_strategies:
    enabled: true                   # 启用回退策略
    
    # 结果不足时的回退
    insufficient_results:
      strategy: "expand_search"      # 回退策略: expand_search, lower_threshold, cached_results
      expand_factor: 1.5            # 扩展因子
      min_threshold_reduction: 0.1  # 最小阈值降低
      max_iterations: 3             # 最大迭代次数
    
    # 质量不达标时的回退
    quality_fallback:
      strategy: "mixed_results"      # 回退策略: lower_standards, mixed_results, cached_backup
      quality_reduction: 0.2        # 质量标准降低
      mix_ratio: 0.7                # 混合比例
    
    # 超时时的回退
    timeout_fallback:
      strategy: "cached_results"     # 回退策略: cached_results, partial_results, error
      cache_max_age: 86400          # 缓存最大年龄(秒)
      partial_min_results: 1        # 部分结果最小数量
  
  # 监控和日志配置
  monitoring:
    enabled: true                   # 启用监控
    
    # 指标收集
    metrics:
      enabled: true                 # 启用指标收集
      collection_interval: 60       # 收集间隔(秒)
      metrics_to_collect:
        - "response_time"
        - "result_count"
        - "quality_score"
        - "diversity_score"
        - "filter_rate"
        - "fallback_rate"
    
    # 告警配置
    alerts:
      enabled: true                 # 启用告警
      thresholds:
        high_response_time: 10.0    # 高响应时间阈值(秒)
        low_result_count: 2         # 低结果数量阈值
        low_quality_score: 0.4      # 低质量分数阈值
        high_filter_rate: 0.8       # 高过滤率阈值
        high_fallback_rate: 0.5     # 高回退率阈值
    
    # 日志配置
    logging:
      enabled: true                 # 启用日志
      log_level: "INFO"             # 日志级别
      log_format: "json"            # 日志格式: text, json
      include_request_details: true # 包含请求详情
      include_performance_metrics: true # 包含性能指标
      log_filtered_content: false   # 记录被过滤的内容
  
  # 调试配置
  debug:
    enabled: false                  # 启用调试模式
    verbose_logging: false          # 详细日志
    save_intermediate_results: false # 保存中间结果
    performance_profiling: false    # 性能分析
    memory_tracking: false          # 内存跟踪