datasets:
  narrativeqa:
    retrievers: ["hybrid"]
    readers: ["vllm", "openai"]
openai:
  answer_prompt_name: answerer_openai.txt
  model: deepseek-chat
  api_key: "sk-c003ed6c90c24b5f8caad6252b4d6a24"
  api_key_env: "OPENAI_API_KEY"
  base_url: https://api.deepseek.com/v1
